name = "backend"
main = "dist/server-phase2.js"
compatibility_date = "2025-09-06"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"

[vars]
PORT = "8080"
API_PORT = "8080"
BACKEND_PORT = "3000"
HOST = "0.0.0.0"
NODE_ENV = "production"
API_VERSION = "v1"

STELLAR_NETWORK = "mainnet"
STELLAR_HORIZON_URL = "https://horizon.stellar.org"
NETWORK = "mainnet"
RPC_URL = "https://mainnet.sorobanrpc.com"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

KALE_CONTRACT_ID = "CDL74RF5BLYR2YBLCCI7F5FB6TPSCLKEJUBSD2RSVWZ4YHF3VMFAIGWA"
CONTRACT_ID = "CDL74RF5BLYR2YBLCCI7F5FB6TPSCLKEJUBSD2RSVWZ4YHF3VMFAIGWA"

POOL_NAME = "KALE Pool Alpha"
POOL_FEE = "0.05"
MIN_STAKE = "1"
MAX_STAKE = "1000"
POOLER_ID = "12345678-1234-5678-9abc-123456789000"
POOL_REWARD_PERCENTAGE = "0.60"

MAX_FARMERS_PER_REQUEST = "100"
API_RATE_LIMIT = "1000"
REQUEST_TIMEOUT = "30000"

LOG_LEVEL = "debug"
ENABLE_METRICS = "true"
HEALTH_CHECK_ENDPOINT = "/health"

RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"

CORS_ORIGIN = "http://localhost:8080"
CORS_METHODS = "GET,POST,PUT,DELETE,OPTIONS"
CORS_HEADERS = "Origin,X-Requested-With,Content-Type,Accept,Authorization"

ENV = "mainnet"
LAUNCHTUBE_URL = "https://launchtube.xyz"
STAKE_AMOUNT = "12"
NONCE_COUNT = "10000000"
